### PR TITLE
Add contact page

### LINKED ISSUE #44: Add Riot community page
I'd like to add this to the main page, right underneath our community e-mail address.. Is that OK?
 Or better in another place?

Chat channels - https://riot.im/app/#/group/+osmbe:matrix.org

### PR DESCRIPTION
**Pull request by jbelien**
Close #44

### CODE REVIEW

**Comment by jbelien** [comment]
I added the Contact page !
Could you review it and translate the `contact-nl.html` ?

Thanks :)

**Comment by joostschouppe** [comment]
I translated the Dutch version, removed the mailto:mailing list, because that doesn't actually work. And I've added the community e-mail address, because we can't promote that enough. I didn't touch the other language versions though.

**Comment by jbelien** [comment]
I update `fr` and `en` :)
Thanks for the translation !

**Comment by jbelien** [comment]
Okay to merge it ? 😃 

Ping @joostschouppe @xivk

**Pull request merged**
