### PR TITLE
Create 2017-01-19-en-motm-Steve-All.md

### PR DESCRIPTION
**Pull request by marcgemis**
New mapper of the month article. But I cannot place the image file in the images directory.

### CODE REVIEW

**Comment by jbelien** [comment]
Hi @marcgemis ,

Please attach file to a comment here. I'll add the image to the article and publish everything :)

**Comment by marcgemis** [comment]
Here's the file
img_0214

**Comment by jbelien** [comment]
Your article is online !
Thanks a lot :)

**Comment by marcgemis** [comment]
Something went wrong with the first few lines. I should have dropped the
title I guess. And the first question is not in bold.

**Comment by jbelien** [comment]
Indeed, I'll fix that right now !

**Comment by marcgemis** [comment]
do I create a fork ?

**Comment by jbelien** [comment]
No need, it's fixed :)

**Comment by marcgemis** [comment]
thanks a lot.

**Comment by marcgemis** [comment]
Sorry to bother you again, but there is aproblem with the link for

 As we dialog on [talk-us pages] (
https://lists.openstreetmap.org/pipermail/talk-us/2014-December/thread.html
)

**Comment by jbelien** [comment]
I'll check and fix that ^^

**Comment by jbelien** [comment]
Fixed !

I also fixed <http://bestofosm.org/#best-of-us-santa-cruz> link, a link without a text must be between `<...>` :)

**Pull request merged**
